insert into clubs values('Авиамоделирование',                       'Отсутствует',                   '13');                  
insert into clubs values('Театральное искусство',                   'Для ребят от 3-х лет',          '12');                  
insert into clubs values('Хоровое пение',                           'Отсутствует',                   '10');                  
insert into clubs values('Сольное пение',                           'Для ребят от 4-х лет',          '11');                  
insert into clubs values('Классические танцы',                      'Для ребят от 3-х лет',          '9' );                  
insert into clubs values('Кружок общего дошколього развития',       'Отсутствует',                   '8' );                  
insert into clubs values('Спортивный куржок',                       'Отсутствует',                   '7' );                  
insert into clubs values('Начальные естественные науки',            'Для ребят от 4-х лет',          '6' );                  
insert into clubs values('Начальные филологические науки',          'Для ребят от 4-х лет',          '5' );                  
insert into clubs values('Кружок художественного чтения',           'Для ребят от 4-х лет',          '4' );                  